### ISSUE TITLE
IDs falsely reported in attribute selectors

### ISSUE THREAD

**Issue by csswizardry** [katiefenn/parker#28]
These two selectors have the same specificity ([jsFiddle](http://jsfiddle.net/12af3svc/)):

```
[href="#main"] {
    color: red;
}

.link {
    color: green;
}
```

However, I think Parker is reporting `[href="#main"]` as being an ID. When running Parker over a stylesheet containing *only* the above CSS (abridged for brevity):

```
PARKER-JS
Total Stylesheets: 1
Total Stylesheet Size: 64
Total Rules: 2
Total Selectors: 2
Total Identifiers: 3
Total Declarations: 2
Selectors Per Rule: 1
Identifiers Per Selector: 1.5
Specificity Per Selector: 55.5
Top Selector Specificity: 101
Top Selector Specificity Selector: [href="#main"]
Total Id Selectors: 1
...
```

**Comment by callumacrae** [comment]
@csswizardry I guess you didn't get a notification for this, but I just submitted a fix for this (among with a fix for my own bug) in #35.
