### ISSUE TITLE
Parker fails on all css: No valid stylesheet data supplied

### ISSUE THREAD

**Issue by ideamonk** [katiefenn/parker#33]
```
$ parker screen.css
/usr/local/lib/node_modules/parker/lib/Parker.js:32
    throw {'message': 'No valid stylesheet data supplied', 'name': 'DataTypeEx
    ^
```

**Comment by clemens-tolboom** [comment]
I get same error using `parker dir/file.css` My file is minified came from sass workflow using grunt.

**Comment by bartveneman** [comment]
Is this still problematic? Otherwise I propose to close this issue.

**Comment by clemens-tolboom** [comment]
Dunno. Its ages ago with that particular stylesheet. Currently `parker src/style.css` runs successful.

**Comment by kitation** [comment]
Ok, will close if the issue doesn't stand. If it reoccurs, please give us an example of the stylesheet that's breaking so we can test. Thanks!
