### ISSUE TITLE
Recursively parse folder

### ISSUE THREAD

**Issue by tzi** [katiefenn/parker#41]
Hi ! 

Thanks for sharing & maintaining this tool.

In a project, we have a deep folder architecture.
Parker seems to only parse stylesheets that are directly in the CSS root folder.

Cheers,
Thomas.

**Comment by bartveneman** [comment]
Is it actually useful to run Parker on multiple files? I understand that this might be useful for concatenated files or partial files, but I don't think it's a good idea to run Parker on *all* your source files, because then you'd have to review all of them instead of a couple of bigger files, which is a lot easier and less time consuming.

**Comment by tzi** [comment]
Hi @bartveneman!

I think it could be interesting to follow some values for the entire code base:
 * Total rules
 * Unique colors
 * Unique media queries

But it also a great feature to be able to parse one file to review it.

Cheers,
Thomas.

**Comment by bartveneman** [comment]
It isn't so hard to setup [a build process](http://alfanso.com/minify-your-final-css-file-using-gulp-js/) so all files get [merged into one file](https://www.npmjs.com/package/gulp-concat-css), right? I don't think scanning directories is a responsibility of Parker but of us developers. Glad to help if you need some :)

**Comment by tzi** [comment]
My css files are merged into a single file... but only during the deployment process ;)
I don't need to merge it on my local computer.

I understand you don't need this features. Perhaps it's not the case for everyone.
For example, feature like #3 Sass support will certainly need it.

Cheers,
Thomas.

**Comment by bartveneman** [comment]
Just trying to come up with a possible solution or improvement. Isn't it possible and maybe better to let Parker run in your build step?

**Comment by danez** [comment]
We had the same problem and made parker glob-aware. The only limitation currently is, that some files might be read multiple times, when mixing glob-paths and non-glob-paths.

https://github.com/researchgate/parker/tree/accept-glob-args

**Comment by tzi** [comment]
@danez I made a PR (#42) for recursive folder parsing.
Don't hesitate to try it... and upvote it ;)
