### ISSUE TITLE
zsh: command not found

### ISSUE THREAD

**Issue by rlahoda** [katiefenn/parker#45]
I'm pretty sure this is an issue on my computer only, but it doesn't make sense. I just installed Parker on a desktop mac and everything went fine. Tried to do the same on my laptop and i get "`zsh: command not found: parker`". I pasted in `npm install -g parker` on both of them and it says it installed correctly, but it's not working when I try to use it. Any ideas?

**Comment by bartveneman** [comment]
- Does `parker -v` also throw an error?
- Does restarting the terminal or even the computer help?

**Comment by rlahoda** [comment]
parker -v doesn't work and restarting the terminal and computer didn't work. I even went into my npm global folder and deleted the files and reinstalled. I don't get it since i'm not having issues otherwise. I did just notice that `-v` doesn't work on eslint, jslint or parker so I'm wondering if there's something else going on. I checked to make sure it was installing to the correct location, my zshrc is pointing in the right location, npmrc is pointing in the right location. I think my computer just hates me right now or something.

**Comment by davidpelayo** [comment]
I think this hasn't have to do with the parker repo. I suggest to look for solutions in other platforms and close this issue.

**Comment by rlahoda** [comment]
Unless I find something that points to an issue with Parker, I agree this probably is a different issue. Thanks.

**Comment by rlahoda** [comment]
FYI. This past weekend I wiped my laptop clean and reinstalled everything and Parker is working fine. I suspect that something random was conflicting with it and caused the issue so yeah, not a problem with the repo.

**Comment by bartveneman** [comment]
Great to hear it's working again anyway 😄
